/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yc_com_app_biz_ndk_JniTest */

#ifndef _Included_yc_com_app_biz_ndk_JniTest
#define _Included_yc_com_app_biz_ndk_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yc_com_app_biz_ndk_JniTest
 * Method:    getStrFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_yc_com_app_biz_ndk_JniTest_getStrFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
